// mfe3-react/src/App.jsx
import React, { Suspense, useEffect, useState } from "react";
import ReactDOM from "react-dom/client";
import { Provider, useDispatch } from "react-redux";
import { BrowserRouter, Route, Routes, useNavigate } from "react-router-dom";
import { filter } from "rxjs";
import { Home } from "./Home";
import { Page1 } from "./Page1";
import { Page2 } from "./Page2";
import { useUsername } from "./hooks/useState.ts";
import { setUsername } from "shared-state-lib";
import "./index.css";

const NavigationDivs = () => {
  const navigate = useNavigate();

  useEffect(() => {
    const subscription = window.AngularRouter.events
      .pipe(filter((e) => e instanceof window.NavigationEnd))
      .subscribe((event) => {
        navigate(event?.urlAfterRedirects);
        console.log("REACT - ", event);
      });

    return () => {
      subscription.unsubscribe();
    };
  }, [navigate]);

  return (
    <div style={{ display: "flex", padding: 10, gap: "10px" }}>
      <div onClick={() => navigate("/mfe3-react/nav1")} className="nav-card">
        Navegação 1
      </div>
      <div onClick={() => navigate("/mfe3-react/nav2")} className="nav-card">
        Navegação 2
      </div>
    </div>
  );
};

export const App = () => {
  const username = useUsername();

  const handleChange = (event) => {
    setUsername(event.target.value);
  };

  return (
    <div className="container">
      <div className="title">
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg"
          height="50"
        />
        <span style={{ fontWeight: "bold" }}>Aplicação React</span>
      </div>
      <p>Username: {username}</p>
      {/* <p>Versão: {React.version}</p> */}
      {/* <Button /> */}
      <NavigationDivs />

      <Routes>
        <Route path="/mfe3-react" element={<Home />} />
        <Route path="/mfe3-react/nav1" element={<Page1 />} />
        <Route path="/mfe3-react/nav2" element={<Page2 />} />
      </Routes>

      {/* <label htmlFor="nome">
        <input
          id="nome"
          type="text"
          placeholder="Nome do usuário"
          onChange={handleChange}
        />
      </label> */}
    </div>
  );
};

const RootComponent = () => (
  <BrowserRouter>
    <Suspense fallback={<div>Loading</div>}>
      <App />
    </Suspense>
  </BrowserRouter>
);

class ReactElement extends HTMLElement {
  connectedCallback() {
    this._root = ReactDOM.createRoot(this);
    this._root.render(<RootComponent />);
  }
}

customElements.define("mfe3_react-element", ReactElement);

// mfe4-vue/src/App.vue
<script setup>
import { RouterLink, RouterView, useRouter } from "vue-router";
import { ref, onMounted, onUnmounted } from "vue";
import { filter } from "rxjs";
import { getUsernameObservable } from "shared-state-lib";

const router = useRouter();
const username = ref("");

const username$ = getUsernameObservable();

const usernameSubscription = username$.subscribe((value) => {
  username.value = value;
});

onMounted(() => {
  // if (window.AngularRouter && window.AngularRouter.events) {
  //   const angularSubscription = window.AngularRouter.events
  //     .pipe(filter((e) => e instanceof window.NavigationEnd))
  //     .subscribe((event) => {
  //       router.push(event?.urlAfterRedirects);
  //       console.log("VUE - ", event);
  //     });

  //   onUnmounted(() => {
  //     angularSubscription.unsubscribe();
  //     usernameSubscription.unsubscribe();
  //   });
  // } else {
  //   console.error("AngularRouter não está disponível.");
  // }
});
</script>

<template>
  <div class="container">
    <div class="title">
      <img
        width="65"
        height="60"
        src="https://img.icons8.com/color/48/vue-js.png"
        alt="vue-js"
      />
      <span>Aplicação Vue</span>
    </div>
    <p>Username: {{ username }}</p>
    <!-- <div>Name: mfe4-vue</div> -->
    <div style="display: grid; padding: 5px; gap: 10px">
      <RouterLink to="/mfe4-vue">Go to Home</RouterLink>
      <RouterLink to="/mfe4-vue/page1">Pagina 1</RouterLink>
      <RouterLink to="/mfe4-vue/page2">Pagina 2</RouterLink>
    </div>

    <RouterView id="app"></RouterView>
  </div>
</template>
